### ISSUE TITLE
Lazy Loading (Adding children and refreshing data dynamically)

### ISSUE THREAD

**Issue by bazahmed** [yWorks/yfiles-for-html-demos#10]
Hello! I was wondering if it is possible to add children to a node and refresh the orgchart with new data dynamically?

**Comment by yGuy** [comment]
Yes, that is possible: https://docs.yworks.com/yfileshtml/#/dguide/layout-summary#layout-incremental_layout

Actually if you collapse and expand the nodes with the little plus/minus icon in the organization chart, this is exactly what happens, already. 

In this specific case the data is already loaded, but it could just as well be fetched from the server, dynamically.
