### ISSUE TITLE
Cannot enable undo capabilities for grouped graph

### ISSUE THREAD

**Issue by ingrid0404** [yWorks/yfiles-for-html-demos#19]
I was trying to enable undo and redo as shown in demo [https://live.yworks.com/demos/tutorial-yfiles-basic-features/07-undo-clipboard-support/](url)
I the graph is an instance of DefaultGraph everything works as expected, but if I use a grouped graph I get the following error in console:

constructor {message: "Affected parameter graph: Provided graph can't provide undo support", name: 'ArgumentError', cause: null, stack: 'ArgumentError: Affected parameter graph: Provided …les/react-dom/cjs/react-dom.development.js:90:45)'}
cause:null
message: "Affected parameter graph: Provided graph can't provide undo support"
name:"ArgumentError"

**Comment by yGuy** [comment]
As far as I understand, this is not a bug report for the mentioned demo, but rather a request to help you with your implementation. As such, the GitHub issues is not the right place, as this is not an issue with the code in this repository.
Please turn to our support team to get support for yFiles, instead. Thanks!

That said - if this is about folding, enable undo on the graph that backs the folded graph: 

https://github.com/yWorks/yfiles-for-html-demos/blob/84208e2422d4260fd230639a5aa6455097a8c4db/demos/application-features/folding/FoldingDemo.js#L92C59-L92C59

**Comment by ingrid0404** [comment]
Thank you for the quick response.
