### ISSUE TITLE
Drag and drop for restructure org chart 

### ISSUE THREAD

**Issue by caeserbala** [yWorks/yfiles-for-html-demos#3]
Hi Team ,
Current Org chart support drag and drop external components as per demo . 
I need feature where we can drag and drop org chart node within orgchart .

like Manager -> TL -> employee 
Manager -> employee  -> TL

**Comment by yGuy** [comment]
This feature can be added using the library and through customizing the input mode. The current demo is a read-only view organization chart. So this is a missing feature. We are considering adding a more complete organization chart demo that allows for editing the chart in the future. In the meantime, you will have to add this feature yourself or contact our support team.
