### ISSUE TITLE
2.3version Context Menu Demo has bug

### ISSUE THREAD

**Issue by CarryM** [yWorks/yfiles-for-html-demos#5]
**Describe the bug**
Right-click the invalid

**To Reproduce**
1. Go to 'Context Menu Demo'
2. Click on 'node'
3. There was no reaction

**Expected behavior**
fix bug .

**Screenshots**
![image](https://user-images.githubusercontent.com/30335440/86564260-7eb5cf80-bf98-11ea-8534-2987936edadb.png)

**Browser (please complete the following information):**
 - Version [e.g. 22.42]
 - OS: [mac 10.15.5]

**Additional context**

**Comment by michabaur** [comment]
Thanks for your bug report. We already noticed the problem, too, and fixed it in the latest release: https://www.yworks.com/products/yfiles-for-html/changelog#v2_3_0_1_demos
