### ISSUE TITLE
build files zoom bug

### ISSUE THREAD

**Issue by CarryM** [yWorks/yfiles-for-html-demos#7]
**Describe the bug**
when npm run build ,yfiles on zoomIn will lost some items 

**To Reproduce**
1.just zoomIn 

**Expected behavior**
should like localhost project

**Screenshots**
![image](https://user-images.githubusercontent.com/30335440/89792394-1342bd00-db57-11ea-944f-266737f5d3b4.png)
![image](https://user-images.githubusercontent.com/30335440/89792412-1a69cb00-db57-11ea-8367-afc70b35095d.png)

**Browser (please complete the following information):**
 - Version [e.g. 22.42]
 - OS: [e.g. Windows]

**Additional context**
please reply quickly

**Comment by yGuy** [comment]
First of all: "additional context: please reply quickly" made me laugh out loud. That is not additional context that will help *us* to reproduce the problem you are seeing. If you want quick help, please use our support services available on https://my.yworks.com  - as the template (that you deleted)says, this is not a support forum and even if this was a properly formulated support question, this is not the right place to get help for implementation issues. If you find a bug with the demo, feel free to post it here, but the sources are mainly meant as a reference and the issues are not meant to store your implementation issue. Thank you for your understanding. 

With that being said, I believe (I cannot be sure, but as you will probably understand a screen-shot taken with a mobile phone of a screen rendering alone does not make for a reproducible test-case) that you are running into this issue: https://docs.yworks.com/yfileshtml/#/kb/article/771/Graph_elements_disappear_or_appear_cutoff

If you want further help, I suggest you work on these parts of your "submission":

> when npm run build ,yfiles on zoomIn will lost some items

Which package json did you run npm build?

>To Reproduce
>Steps to reproduce the behavior:
>1.just zoomIn

Which demo should we just zoom in - all the demos that I have tried work flawlessly. Which exact version of yFiles are you using?

>Expected behavior
>should like localhost project

What?

**Comment by CarryM** [comment]
it works,thanks
